"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo } from "react";

type ReceiptViewModel = {
  id: string;
  receiptNumber: string;
  paymentDate: string;
  amount: number;
  paymentMethod?: string;
  notes?: string;
  policyNumber?: string;
  coverageType?: string;
  coverageStartDate?: string;
  coverageEndDate?: string;
  outstandingBalanceAfter?: number;
  customerName?: string;
  customerEmail?: string;
  customerContact?: string;
  generatedByName?: string;
};

type Props = {
  receipt: ReceiptViewModel;
  backHref?: string;
};

export function ReceiptViewer({ receipt, backHref }: Props) {
  const router = useRouter();

  const formattedDate = useMemo(
    () => new Date(receipt.paymentDate).toLocaleString(),
    [receipt.paymentDate],
  );

  const handlePrint = () => {
    window.print();
  };

  const handleExportPdf = () => {
    // Rely on the browser's print-to-PDF capability for a quick export.
    window.print();
  };

  const handleBack = () => {
    if (backHref) {
      router.push(backHref);
      return;
    }
    router.back();
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2 print:hidden">
        <button className="btn btn-primary" onClick={handlePrint}>
          Print
        </button>
        <button className="btn" onClick={handleExportPdf}>
          Export PDF
        </button>
        <button className="btn" onClick={handleBack}>
          Go back
        </button>
        <Link href="/receipts" className="btn">
          Receipts list
        </Link>
      </div>

      <div className="receipt-paper">
        <div className="flex flex-col items-center gap-2 text-center">
          <img
            src="/IC-LOGO-NEW.png"
            alt="Combined Insurance Services"
            className="h-64 w-auto object-contain -mt-2"
          />
          <h2 className="text-2xl font-bold text-[var(--ic-navy)] tracking-tight">Payment Receipt</h2>
          <div className="grid w-full gap-3 rounded-md border border-[var(--ic-gray-200)] bg-[var(--ic-gray-50)] p-3 text-xs font-semibold text-[var(--ic-gray-700)] leading-snug md:grid-cols-3">
            <div className="text-left space-y-0.5">
              <p>P.O. GM 636, Gablewoods Mall</p>
              <p>Castries, St. Lucia</p>
              <p>Tel: 758 456-0700</p>
            </div>
            <div className="text-center space-y-0.5">
              <p>Garvey Street</p>
              <p>Vieux Fort</p>
              <p>Tel: 454-5415</p>
            </div>
            <div className="text-right space-y-0.5">
              <p>Bridge Street</p>
              <p>Soufriere</p>
              <p>Tel: 457-1500</p>
            </div>
          </div>
        </div>

        <div className="mt-4 rounded-md border border-[var(--ic-gray-200)] bg-[var(--ic-gray-50)] px-3 py-2 text-sm text-[var(--ic-gray-700)]">
          <p className="font-semibold text-[var(--ic-navy)]">Receipt: {receipt.receiptNumber}</p>
          <p>Date: {formattedDate}</p>
          <p>Generated by: {receipt.generatedByName || "—"}</p>
        </div>

        <div className="mt-6 grid gap-4 md:grid-cols-2">
          <div className="info-card">
            <h3>Customer</h3>
            <p className="primary">{receipt.customerName || "—"}</p>
            <p>{receipt.customerEmail || "—"}</p>
            <p>{receipt.customerContact || "—"}</p>
          </div>
          <div className="info-card">
            <h3>Policy</h3>
            <p className="primary">Policy: {receipt.policyNumber || "—"}</p>
            <p>Coverage: {receipt.coverageType || "—"}</p>
            <p>
              Coverage dates:{" "}
              {receipt.coverageStartDate
                ? new Date(receipt.coverageStartDate).toLocaleDateString()
                : "—"}{" "}
              to{" "}
              {receipt.coverageEndDate
                ? new Date(receipt.coverageEndDate).toLocaleDateString()
                : "—"}
            </p>
          </div>
        </div>

        <div className="mt-6 rounded-lg border border-[var(--ic-gray-200)] p-4">
          <div className="grid gap-4 md:grid-cols-3">
            <div>
              <p className="label">Payment method</p>
              <p className="value">{receipt.paymentMethod || "—"}</p>
            </div>
            <div>
              <p className="label">Amount</p>
              <p className="value text-2xl">${receipt.amount.toFixed(2)}</p>
            </div>
            <div>
              <p className="label">Outstanding after payment</p>
              <p className="value">
                {typeof receipt.outstandingBalanceAfter === "number"
                  ? `$${receipt.outstandingBalanceAfter.toFixed(2)}`
                  : "—"}
              </p>
            </div>
          </div>
          {receipt.notes && (
            <div className="mt-4 rounded-md bg-[var(--ic-gray-50)] p-3 text-sm text-[var(--ic-gray-800)]">
              <p className="font-semibold text-[var(--ic-navy)]">Notes</p>
              <p>{receipt.notes}</p>
            </div>
          )}
        </div>

        <div className="mt-8 grid gap-6 md:grid-cols-2">
          <div className="signature-box">
            <p className="label">Received by</p>
            <div className="sig-line" />
            <p className="muted">{receipt.generatedByName || "Name"}</p>
          </div>
          <div className="signature-box">
            <p className="label">Customer</p>
            <div className="sig-line" />
            <p className="muted">{receipt.customerName || "Name"}</p>
          </div>
        </div>
      </div>

    </div>
  );
}

